version: "3.8"

services:
  api:
    image: ghcr.io/yohanaaaaaa/saudavelmente/saudavelmente-api:latest
    ports:
      - "4000:3007"
    environment:
      NODE_ENV: production
      PORT: 3007
      DATABASE_URL: ${DATABASE_URL}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
