version: "3.8"

services:
  api:
    build: .
    container_name: saudavelmente-api
    restart: always
    ports:
      - "4000:3007"   # fora 4000 / dentro 3007
    environment:
      NODE_ENV: production
      PORT: 3007
      DATABASE_URL: ${DATABASE_URL}
